server:
  port: 8000

spring:
  application:
    name: Resource Server

security:
  oauth2:
    client:
      client-id: test
      client-secret: 123456
    resource:
      check-token-uri: http://localhost:9001/oauth/check_token
      token-info-uri:  http://localhost:9001/oauth/check_token


